webapp-travel-agency/Models/Travel.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace webapp_travel_agency.Models
{
    public class Travel
    {
        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "Il nome non può avere più di 50 caratteri")]
        public string Name { get; set; }
        public string Photo { get; set; }

        [Column(TypeName = "text")]
        public string Description { get; set; }

        [Range(1, 999, ErrorMessage = "La durata del viaggio non può essere inferiore a 1")]
        public int Day { get; set; }
        public int Destination { get; set; }

        [Range(1, 999, ErrorMessage = "Il prezzo non può essere inferiore a 1")]
        public int Price { get; set; }
            
        public List<Message>? Messages { get; set; }
        public Travel()
        {

        }
        public Travel(string name, string description, int day, int price)
        {
            Name = name;
            Description = description;
            Day = day;
            Price = price;
        }
    }
}

webapp-travel-agency/Controllers/Admin/TravelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp_travel_agency.Data;
using webapp_travel_agency.Models;

namespace webapp_travel_agency.Controllers.Admin
{
    public class TravelController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TravelController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Travel
        public async Task<IActionResult> Index()
        {
            return View(await _context.Travels.ToListAsync());
        }

        // GET: Travel/Detail/5
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null || _context.Travels == null)
            {
                return NotFound();
            }

            var travel = await _context.Travels.FirstOrDefaultAsync(m => m.Id == id);
            if (travel == null)
            {
                return NotFound();
            }

            return View(travel);
        }

        // GET: TravelBoxes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TravelBoxes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Travel travel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(travel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(travel);
        }

        // GET: TravelBoxes/Edit/5
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null || _context.Travels == null)
            {
                return NotFound();
            }

            var travel = await _context.Travels.FindAsync(id);
            if (travel == null)
            {
                return NotFound();
            }
            return View(travel);
        }

        // POST: TravelBoxes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Travel travel)
        {
            if (id != travel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(travel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelExists(travel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(travel);
        }

        // GET: TravelBoxes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Travels == null)
            {
                return NotFound();
            }

            var travelBox = await _context.Travels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (travelBox == null)
            {
                return NotFound();
            }

            return View(travelBox);
        }

        // POST: TravelBoxes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Travels == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Travel'  is null.");
            }
            var travelBox = await _context.Travels.FindAsync(id);
            if (travelBox != null)
            {
                _context.Travels.Remove(travelBox);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TravelExists(int id)
        {
            return _context.Travels.Any(e => e.Id == id);
        }
    }
}

webapp-travel-agency/Controllers/Api/TravelController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp_travel_agency.Data;
using webapp_travel_agency.Models;

namespace webapp_travel_agency.Controllers.Api
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class TravelController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public TravelController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/TravelApi
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Travel>>> GetTravel()
        {
            return await _context.Travels.ToListAsync();
        }

        // GET: api/TravelApi/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Travel>> GetTravel(int id)
        {
            var travel = await _context.Travels.FindAsync(id);

            if (travel == null)
            {
                return NotFound();
            }

            return travel;
        }

        // PUT: api/TravelApi/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutTravel(int id, Travel travel)
        {
            if (id != travel.Id)
            {
                return BadRequest();
            }

            _context.Entry(travel).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TravelExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/TravelApi
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Travel>> PostTravel(Travel travel)
        {
            _context.Travels.Add(travel);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetTravelBox", new { id = travel.Id }, travel);
        }

        // DELETE: api/TravelBoxesApi/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTravel(int id)
        {
            var travel = await _context.Travels.FindAsync(id);
            if (travel == null)
            {
                return NotFound();
            }

            _context.Travels.Remove(travel);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool TravelExists(int id)
        {
            return _context.Travels.Any(e => e.Id == id);
        }
    }
}

webapp-travel-agency/Views/Travel/Create.cshtml
@model Travel

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Crea un nuovo viaggio/destinazione:</h1>
            </div>
            <form asp-controller="Travel" asp-creation="Create" method="post">
                @Html.AntiForgeryToken()

                <div class="mb-3">
                    <strong>Nome Viaggio:</strong>
                    <input asp-for="Name" class="d-block w-100" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Foto anteprima destinazione:</strong>
                    <input asp-for="Photo" class="d-block w-100" />
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Descrizione del viaggio:</strong>
                    <textarea asp-for="Description" rows="10" class="d-block w-100"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Durata del viaggio:</strong>
                    <input asp-for="Day" class="d-block w-100" />
                    <span asp-validation-for="Day" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Numero di destinazioni del viaggio:</strong>
                    <input asp-for="Destination" class="d-block w-100" />
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Costo del viaggio:</strong>
                    <input asp-for="Price" class="d-block w-100" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>
            </form>
        </div>
    </div>
</div>

webapp-travel-agency/Views/Travel/Detail.cshtml
@model Travel
@{
    int count = 0;
}
<div class="travelCard">
    <span class="invisible">@count</span>
    <img src="@Model.Photo">
    <h2>@Model.Name</h2>
    <p>@Model.Description</p>
    <p>Giorni totali del viaggio: @Model.Day</p>
    <p>Destinazioni del viaggio: @Model.Destination</p>
    <p>Prezzo: @Model.Price €</p>
    <div>
</div>

webapp-travel-agency/Views/Travel/Index.cshtml
@model IEnumerable<Travel>
@{
    int count = 0;
}
<div class="title">
    <h1>Our Amazing Tours</h1>
</div>

<div class="create">
    <a class="btn btn-primary" href="@Url.Action("Create", "Travel")">Crea un nuovo viaggio</a>
</div>

<div class="travel-section">

    @foreach (Travel travel in Model)
    {
        <div class="travelCard">
            <span class="invisible">@count</span>
            <div class="travelPhoto">
                <img src="@travel.Photo">
            </div>
            <h2>@travel.Name</h2>
            <p>@travel.Description</p>
            <p>Giorni totali del viaggio: @travel.Day</p>
            <p>Destinazioni del viaggio: @travel.Destination</p>
            <p>Prezzo: @travel.Price €</p>
            <td>
                <a class="btn btn-outline-info" asp-action="Detail" asp-route-id="@travel.Id">Detail</a>
                <a class="btn btn-outline-warning" asp-action="Update" asp-route-id="@travel.Id">Update</a>
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@travel.Id">Delete</a>
            </td>
        </div>
    }

</div>

webapp-travel-agency/Views/Travel/Update.cshtml
@model Travel

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Modifica il viaggio/destinazione:</h1>
            </div>
            <form asp-controller="Travel" asp-creation="Update" asp-route-id="@Model.Id" method="post">
                @Html.AntiForgeryToken()

                <div class="mb-3">
                    <strong>Nome Viaggio:</strong>
                    <input asp-for="Name" class="d-block w-100" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Foto anteprima destinazione:</strong>
                    <input asp-for="Photo" class="d-block w-100" />
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Descrizione del viaggio:</strong>
                    <textarea asp-for="Description" rows="10" class="d-block w-100"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Durata del viaggio:</strong>
                    <input asp-for="Day" class="d-block w-100" />
                    <span asp-validation-for="Day" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Numero di destinazioni del viaggio:</strong>
                    <input asp-for="Destination" class="d-block w-100" />
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <strong>Costo del viaggio:</strong>
                    <input asp-for="Price" class="d-block w-100" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>
            </form>
        </div>
    </div>
</div>